# Generated by Django 3.1.6 on 2021-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wspdv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.IntegerField(unique=True, verbose_name='codigo'),
        ),
    ]
