# Generated by Django 3.1.6 on 2021-05-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='codigo')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao')),
                ('preco', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='preco')),
            ],
        ),
    ]
